/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cadastro_Cliente;

import Login.LoginDAO;
import java.awt.Color;
import java.text.ParseException;
import java.util.Date;
import java.util.Properties;
import javax.mail.Address;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author natalia
 */
public class TelaClientes extends javax.swing.JPanel {
            
    /**
     * Creates new form TelaClientes
     */
    public TelaClientes() throws ParseException {
        initComponents();
        MaskFormatter date = new MaskFormatter("##/##/####");
        date.install(ftxt_DateNasc);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblcadNome = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        lblcadSobreNome = new javax.swing.JLabel();
        txt_sobrenome = new javax.swing.JTextField();
        lbl_Sexo = new javax.swing.JLabel();
        lblcadDataNasc = new javax.swing.JLabel();
        cb_Sexo = new javax.swing.JComboBox<>();
        ftxt_DateNasc = new javax.swing.JFormattedTextField();
        lblcadEmail = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        lblcadSenha = new javax.swing.JLabel();
        ptxt_Senha = new javax.swing.JPasswordField();
        lblcadConfirmaSenha = new javax.swing.JLabel();
        ptxt_ConfirmarSenha = new javax.swing.JPasswordField();
        RB_termos = new javax.swing.JRadioButton();
        btb_cadastrar = new javax.swing.JButton();
        mensagemSistema1 = new projetointegrador1.MensagemSistema();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(230, 230, 230));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 350));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 20));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3);

        lblcadNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcadNome.setText("Nome:");
        lblcadNome.setPreferredSize(new java.awt.Dimension(400, 15));
        jPanel2.add(lblcadNome);

        txt_nome.setBackground(new java.awt.Color(240, 240, 255));
        txt_nome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_nome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nome.setMinimumSize(new java.awt.Dimension(400, 30));
        txt_nome.setPreferredSize(new java.awt.Dimension(400, 30));
        txt_nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_nomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nomeFocusLost(evt);
            }
        });
        jPanel2.add(txt_nome);

        lblcadSobreNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcadSobreNome.setText("Sobrenome:");
        lblcadSobreNome.setPreferredSize(new java.awt.Dimension(400, 15));
        jPanel2.add(lblcadSobreNome);

        txt_sobrenome.setBackground(new java.awt.Color(240, 240, 255));
        txt_sobrenome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_sobrenome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_sobrenome.setPreferredSize(new java.awt.Dimension(400, 30));
        jPanel2.add(txt_sobrenome);

        lbl_Sexo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Sexo.setText("Sexo:");
        lbl_Sexo.setPreferredSize(new java.awt.Dimension(200, 15));
        jPanel2.add(lbl_Sexo);

        lblcadDataNasc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcadDataNasc.setText("Data de nascimento:");
        lblcadDataNasc.setPreferredSize(new java.awt.Dimension(200, 15));
        jPanel2.add(lblcadDataNasc);

        cb_Sexo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cb_Sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Feminino", "Masculino", "Não Informar" }));
        cb_Sexo.setToolTipText("");
        cb_Sexo.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel2.add(cb_Sexo);

        ftxt_DateNasc.setBackground(new java.awt.Color(240, 240, 255));
        ftxt_DateNasc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ftxt_DateNasc.setToolTipText("");
        ftxt_DateNasc.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel2.add(ftxt_DateNasc);

        lblcadEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcadEmail.setText("E-mail:");
        lblcadEmail.setPreferredSize(new java.awt.Dimension(400, 15));
        jPanel2.add(lblcadEmail);

        txt_email.setBackground(new java.awt.Color(240, 240, 255));
        txt_email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_email.setPreferredSize(new java.awt.Dimension(400, 30));
        jPanel2.add(txt_email);

        lblcadSenha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcadSenha.setText("Digite a senha:");
        lblcadSenha.setPreferredSize(new java.awt.Dimension(400, 15));
        jPanel2.add(lblcadSenha);

        ptxt_Senha.setBackground(new java.awt.Color(240, 240, 255));
        ptxt_Senha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ptxt_Senha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ptxt_Senha.setPreferredSize(new java.awt.Dimension(400, 30));
        jPanel2.add(ptxt_Senha);

        lblcadConfirmaSenha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcadConfirmaSenha.setText("Confirme a senha:");
        lblcadConfirmaSenha.setPreferredSize(new java.awt.Dimension(400, 15));
        jPanel2.add(lblcadConfirmaSenha);

        ptxt_ConfirmarSenha.setBackground(new java.awt.Color(240, 240, 255));
        ptxt_ConfirmarSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ptxt_ConfirmarSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ptxt_ConfirmarSenha.setPreferredSize(new java.awt.Dimension(400, 30));
        jPanel2.add(ptxt_ConfirmarSenha);

        RB_termos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RB_termos.setText("Aceito os termos de uso e politica de privacidade");
        RB_termos.setPreferredSize(new java.awt.Dimension(400, 23));
        jPanel2.add(RB_termos);

        btb_cadastrar.setBackground(new java.awt.Color(153, 153, 255));
        btb_cadastrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btb_cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btb_cadastrar.setText("CADASTRAR");
        btb_cadastrar.setPreferredSize(new java.awt.Dimension(200, 30));
        btb_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btb_cadastrarActionPerformed(evt);
            }
        });
        jPanel2.add(btb_cadastrar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 104;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 0);
        jPanel1.add(jPanel2, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.CENTER);
        add(mensagemSistema1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nomeFocusGained
        //txt_nome.setText("Digite seu nome");
    }//GEN-LAST:event_txt_nomeFocusGained

    private void txt_nomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nomeFocusLost
        //txt_nome.setText("Digite seu nome");
    }//GEN-LAST:event_txt_nomeFocusLost

    private void btb_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btb_cadastrarActionPerformed
            ClienteDAO cliente = new ClienteDAO();
            //Validação dos campos    
            if(txt_nome.getText().isEmpty()){
                txt_nome.setBackground(new Color(255, 200, 180));
                mensagemSistema1.setMessageSistema("O campo nome não pode ser vazio!", "error");
            }
            
            if(txt_sobrenome.getText().isEmpty()){
                txt_sobrenome.setBackground(new Color(255, 200, 180));
            }
            
            if(cb_Sexo.getSelectedItem() == "Selecione"){
                cb_Sexo.setBackground(new Color(255, 200, 180));
            }
            
            if(ftxt_DateNasc.getText().isEmpty()){
                ftxt_DateNasc.setBackground(new Color(255, 200, 180));
            }
            
            if(txt_email.getText().isEmpty()){
                txt_email.setBackground(new Color(255, 200, 180));
            }
            
            if(ptxt_Senha.getText().isEmpty()){
                ptxt_Senha.setBackground(new Color(255, 200, 180));
            }
            
            if(ptxt_ConfirmarSenha.getText().isEmpty()){
                ptxt_ConfirmarSenha.setBackground(new Color(255, 200, 180));
            }
            
            if(!RB_termos.isSelected()){
                RB_termos.setBackground(new Color(255, 200, 180));
            }
            Cliente cadCliente = new Cliente();
            ConversorStringDate csd = new ConversorStringDate();
            
            if(cliente.CheckEmail(txt_email.getText())!=true){            
                cadCliente.setNome(txt_nome.getText());
                cadCliente.setSobrenome(txt_sobrenome.getText());
                cadCliente.setSexo(cb_Sexo.getItemAt(cb_Sexo.getSelectedIndex()));
                cadCliente.setDataNasc((java.sql.Date) (Date) csd.convertForward(ftxt_DateNasc.getText()));
                cadCliente.setEmail(txt_email.getText().toLowerCase());
                cadCliente.setSenha(ptxt_Senha.getText());
                cadCliente.setSenhaConfirmacao(ptxt_ConfirmarSenha.getText());    
                if(cliente.inserir(cadCliente)){
                    JOptionPane.showMessageDialog(null,"Bem Vindo " + txt_nome.getText() + "\nTe enviaramos um e-mail em breve!");
                    EnviarEmail();
                    
                }
            }else{
                //JOptionPane.showMessageDialog(null,"E-mail " + txt_email.getText().toUpperCase() + " já existe no sistema");
                mensagemSistema1.setMessageSistema("E-mail " + txt_email.getText().toUpperCase() + " já existe no sistema", "error");
            }
            //cadCliente.setTermos(RB_termos.);
            
            //TelaHome.addCliente.add(cadCliente);            
    }//GEN-LAST:event_btb_cadastrarActionPerformed
    
    public void EnviarEmail(){
        Properties props = new Properties();
        /** Parâmetros de conexão com servidor Gmail */
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.socketFactory.port", "465");
        props.put("mail.smtp.socketFactory.class", 
        "javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.port", "465");

        Session session = Session.getDefaultInstance(props,
          new javax.mail.Authenticator() {
               protected PasswordAuthentication getPasswordAuthentication() 
               {
                     return new PasswordAuthentication("Smartmarketunivem@gmail.com", 
                     "S@martM@rket2019");
               }
          });

        /** Ativa Debug para sessão */
        session.setDebug(true);

        try {

          Message message = new MimeMessage(session);
          message.setFrom(new InternetAddress("Smartmarketunivem@gmail.com")); 
          //Remetente

          Address[] toUser = InternetAddress //Destinatário(s)
                     .parse(txt_email.getText());  

          message.setRecipients(Message.RecipientType.TO, toUser);
          message.setSubject("Bem - Vindo !!");//Assunto
          message.setText("Bem-vindo(a) !\n" + txt_nome.getText());
          /**Método para enviar a mensagem criada*/
          Transport.send(message);

          System.out.println("Feito!!!");

         } catch (MessagingException e) {
            throw new RuntimeException(e);
        }
    }
    public static void main(String args[]) throws ParseException{
        JFrame janela = new JFrame();
        janela.setSize(550, 400);
        
        TelaClientes tela = new TelaClientes();
        janela.add(tela);
        janela.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RB_termos;
    private javax.swing.JButton btb_cadastrar;
    private javax.swing.JComboBox<String> cb_Sexo;
    private javax.swing.JFormattedTextField ftxt_DateNasc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_Sexo;
    private javax.swing.JLabel lblcadConfirmaSenha;
    private javax.swing.JLabel lblcadDataNasc;
    private javax.swing.JLabel lblcadEmail;
    private javax.swing.JLabel lblcadNome;
    private javax.swing.JLabel lblcadSenha;
    private javax.swing.JLabel lblcadSobreNome;
    private projetointegrador1.MensagemSistema mensagemSistema1;
    private javax.swing.JPasswordField ptxt_ConfirmarSenha;
    private javax.swing.JPasswordField ptxt_Senha;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_sobrenome;
    // End of variables declaration//GEN-END:variables
}
