/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mercado;
import Cadastro_Cliente.Cliente;
import java.awt.Color;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.swingbinding.JTableBinding;
import org.jdesktop.swingbinding.SwingBindings;


/**
 *
 * @author Lab04
 */
public class CadastroMercado extends javax.swing.JPanel {

    private List<Mercados> lstMercados;

    /**
     * Creates new form CadastroMercado
     */
    public CadastroMercado(Cliente clienteLogado) {
                lstMercados = new LinkedList<>();
        lstMercados = ObservableCollections.observableList(lstMercados);
        
        initComponents();
        
        BindingGroup bg = new BindingGroup();
        JTableBinding tb = SwingBindings.createJTableBinding(
                    AutoBinding.UpdateStrategy.READ_WRITE,
                    lstMercados, ListM);
        JTableBinding.ColumnBinding mb = tb.addColumnBinding(BeanProperty.create("nome"));
        mb.setColumnName("Nome do Mercado");
        mb.setColumnClass(String.class);
        
        mb = tb.addColumnBinding(BeanProperty.create("URL"));
        mb.setColumnName("URL");
        mb.setColumnClass(String.class);
        
        bg.addBinding(tb);
        
        Binding m;
        m = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE,
                txtMNome, BeanProperty.create("text"),
                ListM, BeanProperty.create("selectedElement.nome"));
        bg.addBinding(m);
        
        m = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE,
                txtURL, BeanProperty.create("text"),
                ListM, BeanProperty.create("selectedElement.url"));
        bg.addBinding(m);
        
        bg.bind();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCNPJ = new javax.swing.JLabel();
        lblLocal = new javax.swing.JLabel();
        txtMNome = new javax.swing.JTextField();
        txtURL = new javax.swing.JTextField();
        btConfirma = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btTermos = new javax.swing.JRadioButton();
        btBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTermos = new javax.swing.JTextArea();
        lblMNome = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListM = new javax.swing.JTable();

        lblCNPJ.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCNPJ.setText("URL:");

        lblLocal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLocal.setText("Lista de Mercados:");

        txtMNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMNomeActionPerformed(evt);
            }
        });

        txtURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtURLActionPerformed(evt);
            }
        });

        btConfirma.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btConfirma.setText("Confirmar");
        btConfirma.setToolTipText("");
        btConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmaActionPerformed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btTermos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btTermos.setText("Aceito os termos de uso e política de privacidade");
        btTermos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTermosActionPerformed(evt);
            }
        });

        btBack.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btBack.setText("Voltar");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        txtTermos.setEditable(false);
        txtTermos.setColumns(20);
        txtTermos.setLineWrap(true);
        txtTermos.setRows(5);
        txtTermos.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas non eleifend lectus, vel tincidunt mauris. Etiam ornare tristique ligula et laoreet. Aliquam condimentum lorem in mauris convallis, vitae consectetur ligula faucibus. Donec orci odio, maximus sed auctor sed, scelerisque ac augue. Fusce non tellus in quam euismod gravida et eget sapien. Maecenas vel magna hendrerit nulla tempor placerat id sed arcu. Nunc felis erat, placerat vehicula tellus eget, mollis fringilla odio. Aenean laoreet, nulla id laoreet lacinia, arcu quam egestas felis, ultrices lobortis felis nunc et metus. Vivamus auctor elit quis volutpat laoreet. Morbi feugiat eros eu laoreet luctus. Pellentesque placerat mi dignissim luctus venenatis.  Proin at tellus luctus, semper felis vitae, pulvinar lacus. Etiam sit amet posuere elit, fermentum pharetra dui. Nam rutrum nibh quis nisi dignissim, condimentum ullamcorper diam sagittis. Quisque suscipit eros ut ligula pharetra, et condimentum neque venenatis. Nullam vitae ex magna. Nam venenatis quam eu dui luctus, ac vehicula magna condimentum. Pellentesque consectetur libero consequat, luctus urna at, vehicula erat. In vitae tristique tortor. Duis ac lacus et magna condimentum ultricies facilisis sit amet sem. Cras sed lacinia erat. Vestibulum dui felis, vulputate pretium efficitur nec, hendrerit aliquet nisi. Aliquam lectus neque, finibus finibus congue gravida, ultrices ac mauris.  Morbi egestas urna hendrerit nibh gravida, a dignissim felis tincidunt. Sed lobortis a quam a convallis. Vestibulum id dignissim tortor. Etiam a est mattis, hendrerit orci ut, tempor justo. Nunc tincidunt nisi non turpis dictum aliquam. Sed placerat tellus consequat mi venenatis condimentum. Cras efficitur lacinia lorem eget suscipit. In hac habitasse platea dictumst. Aliquam erat volutpat. Fusce rhoncus neque at erat ultrices, eget sagittis nunc iaculis.  Maecenas ultrices turpis eget posuere mollis. Quisque vitae egestas justo. Donec sit amet augue massa. Mauris venenatis felis quis tellus bibendum, at maximus libero ultrices. Cras laoreet nunc non imperdiet faucibus. Donec in risus sit amet neque lacinia euismod. Phasellus auctor fringilla elementum. Nunc tempus dui in ligula posuere malesuada. Integer finibus ante eget magna sodales, sed hendrerit sem mattis. Donec vitae massa nisi. Integer metus est, malesuada a tristique non, consequat vitae ante. Pellentesque sit amet molestie nunc. Proin lorem justo, cursus at vulputate nec, porttitor quis risus. Aenean porttitor ante nec sem aliquam, eget scelerisque urna egestas.  Nunc consectetur nisl vitae finibus cursus. Vivamus nec orci commodo, tempus massa id, luctus sapien. Fusce sit amet libero arcu. Etiam ante turpis, varius eu blandit sit amet, gravida sed ligula. Nullam ex arcu, accumsan vel mollis quis, interdum non leo. Mauris mi turpis, bibendum et luctus ut, aliquam vitae lorem. Aenean blandit tempus erat a pretium. Etiam orci nisi, maximus in gravida in, suscipit non risus. Fusce commodo arcu vitae nibh interdum, a commodo velit tempor. Pellentesque tincidunt enim at mi iaculis eleifend. Praesent a nunc faucibus, aliquet nisl quis, pellentesque sem. Aliquam vitae orci sit amet mauris ultricies bibendum vel sit amet tellus. Nulla tristique, est eget semper molestie, lectus sapien blandit libero, id efficitur quam mi nec magna. Suspendisse iaculis scelerisque consectetur. Mauris scelerisque, massa sed sagittis finibus, dui mauris placerat diam, at facilisis urna velit non sem. Fusce tincidunt justo lobortis varius suscipit.  ");
        txtTermos.setToolTipText("");
        jScrollPane2.setViewportView(txtTermos);

        lblMNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMNome.setText("Nome do Mercado:");

        ListM.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ListM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome do Mercado", "URL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(ListM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btExcluir)
                        .addGap(30, 30, 30)
                        .addComponent(btConfirma)
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btTermos)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMNome)
                                    .addComponent(lblCNPJ)
                                    .addComponent(lblLocal))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtURL)
                                    .addComponent(txtMNome)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMNome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCNPJ)
                    .addComponent(txtURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLocal)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(btTermos)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConfirma)
                    .addComponent(btExcluir)
                    .addComponent(btBack))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMNomeActionPerformed

    private void txtURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtURLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtURLActionPerformed

    private void btConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmaActionPerformed

        Mercados tp = new Mercados();
        tp.setNome(txtMNome.getText());

        lstMercados.add(tp);

        MercadoDAO tpd = new MercadoDAO();

        for(Mercados item:lstMercados){
            if(item.getId_Mercado() == null){
                tpd.inserir(item);
            }
        }

        if(txtMNome.getText().trim().isEmpty()&&(txtURL.getText().trim().isEmpty()))
        //jTextField1.setText("Welcome");
        //}
        //else if(jRadioButton2.isSelected()){
            //jTextField1.setText("Hello");

            {
                txtMNome.setBackground(new Color (255, 179, 179));
                txtURL.setBackground(new Color (255, 179, 179));
                JOptionPane.showMessageDialog(null,"Preencha os Campos.", "Erro", JOptionPane.WARNING_MESSAGE);
                txtMNome.setBackground(new Color (255, 255, 255));
                txtURL.setBackground(new Color (255, 255, 255));
            }
            else
            if(txtMNome.getText().trim().isEmpty())
            {
                txtMNome.setBackground(new Color (255, 179, 179));
                JOptionPane.showMessageDialog(null,"Por Favor, insira um Nome.", "Erro", JOptionPane.WARNING_MESSAGE);
                txtMNome.setBackground(new Color (255, 255, 255));
            }
            else
            if(txtURL.getText().trim().isEmpty())
            {
                txtURL.setBackground(new Color (255, 179, 179));
                JOptionPane.showMessageDialog(null,"URL Inválida.", "Erro", JOptionPane.WARNING_MESSAGE);
                txtURL.setBackground(new Color (255, 255, 255));
            }
            else
            if(btTermos.isSelected()){
                Mercados m = new Mercados();
                if(ListM.getSelectedRows().length==0)
                {
                    m.setNome(txtMNome.getText());
                    m.setURL(txtURL.getText());
                }
                lstMercados.add(m);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Você precisa aceitar os termos.", "Erro", JOptionPane.WARNING_MESSAGE);
            }

    }//GEN-LAST:event_btConfirmaActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        int count = ListM.getModel().getRowCount();
        if(count==0)
        {
            JOptionPane.showMessageDialog(null,"A Lista está vazia.", "Erro", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            int idx[] = ListM.getSelectedRows();
            List<Mercados> apagar = new LinkedList<>();
            ListM.getSelectionModel().setSelectionInterval(0,0);
            for(int i=0;i<idx.length;i++){
                int idxTab = idx[i];
                int idxLista = ListM.convertRowIndexToModel(idxTab);
                apagar.add(lstMercados.get(idxLista));
            }

            lstMercados.removeAll(apagar);
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btTermosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTermosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btTermosActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
     
    }//GEN-LAST:event_btBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ListM;
    private javax.swing.JButton btBack;
    private javax.swing.JButton btConfirma;
    private javax.swing.JButton btExcluir;
    private javax.swing.JRadioButton btTermos;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCNPJ;
    private javax.swing.JLabel lblLocal;
    private javax.swing.JLabel lblMNome;
    private javax.swing.JTextField txtMNome;
    private javax.swing.JTextArea txtTermos;
    private javax.swing.JTextField txtURL;
    // End of variables declaration//GEN-END:variables
}
