/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetointegrador1;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author natalia
 */
public class MensagemSistema extends javax.swing.JPanel {

    /**
     * Creates new form MensagemSistema
     */
    public MensagemSistema() {
        initComponents();
        //this.setVisible(false);
    }
    
    public void setMessageSistema(String txt, String type){
        
        ImageIcon icon;
        
        switch(type){
            case "error":
                this.setBackground(new Color(255, 200, 180));
                icon = new ImageIcon(getClass().getResource("/Imagens/cancel_32.png"));
                msg_icon.setIcon(icon);
                break;
            case "success":
                this.setBackground(new Color(200, 255, 180));
                //icon = new ImageIcon(getClass().getResource("/Imagens/checked_32.png"));
                //msg_icon.setIcon(icon);
                break;
            case "loading":
                this.setBackground(new Color(255, 255, 210));
//                icon = new ImageIcon(getClass().getResource("/Imagens/giphy.gif"));
               // msg_icon.setIcon(icon);
                break;
        }
        //this.setVisible(true);
        msg_sistema.setText(txt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msg_icon = new javax.swing.JLabel();
        msg_sistema = new javax.swing.JLabel();
        msg_fechar = new javax.swing.JButton();

        msg_sistema.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        msg_sistema.setForeground(new java.awt.Color(102, 102, 102));

        msg_fechar.setBackground(new java.awt.Color(255, 51, 51));
        msg_fechar.setForeground(new java.awt.Color(255, 255, 255));
        msg_fechar.setText("X");
        msg_fechar.setPreferredSize(new java.awt.Dimension(45, 45));
        msg_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msg_fecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(msg_icon)
                .addGap(18, 18, 18)
                .addComponent(msg_sistema, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msg_fechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(msg_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(msg_fechar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(msg_sistema))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void msg_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msg_fecharActionPerformed
        this.fecharJanela();
    }//GEN-LAST:event_msg_fecharActionPerformed
    
    public void fecharJanela(){
        //this.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton msg_fechar;
    private javax.swing.JLabel msg_icon;
    private javax.swing.JLabel msg_sistema;
    // End of variables declaration//GEN-END:variables
}
