/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import Cadastro_Cliente.Cliente;
import java.awt.Color;
import java.util.Random;
import javax.swing.JFrame;
import projetointegrador1.NewTelaHome;

/**
 *
 * @author natalia
 */
public class TelaLogin extends javax.swing.JPanel {
    
    public Cliente clienteLogado;
    private NewTelaHome newTela;
    
    /**
     * Creates new form TelaLogin
     */
    public TelaLogin(NewTelaHome newTela) {
        initComponents();
        this.newTela = newTela;
    }
    
    /**
     * Creates new form TelaLogin (Para executar com Shift+F6, testes)
     */
    public TelaLogin() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_login = new javax.swing.JTextField();
        ptxt_senha = new javax.swing.JTextField();
        btn_logar = new javax.swing.JButton();
        btb_esqueceu = new javax.swing.JButton();
        mensagemSistema1 = new projetointegrador1.MensagemSistema();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 350));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 10));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cart.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(400, 64));
        jPanel2.add(jLabel2);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Smart Market");
        jLabel1.setMinimumSize(new java.awt.Dimension(400, 43));
        jPanel2.add(jLabel1);

        txt_login.setBackground(new java.awt.Color(240, 240, 255));
        txt_login.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_login.setPreferredSize(new java.awt.Dimension(300, 30));
        jPanel2.add(txt_login);

        ptxt_senha.setBackground(new java.awt.Color(240, 240, 255));
        ptxt_senha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ptxt_senha.setPreferredSize(new java.awt.Dimension(300, 30));
        jPanel2.add(ptxt_senha);

        btn_logar.setBackground(new java.awt.Color(102, 102, 255));
        btn_logar.setForeground(new java.awt.Color(255, 255, 255));
        btn_logar.setText("Entrar");
        btn_logar.setPreferredSize(new java.awt.Dimension(300, 30));
        btn_logar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_logar);

        btb_esqueceu.setBackground(new java.awt.Color(255, 255, 255));
        btb_esqueceu.setForeground(new java.awt.Color(102, 102, 255));
        btb_esqueceu.setText("Esqueceu a senha");
        btb_esqueceu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btb_esqueceu.setBorderPainted(false);
        btb_esqueceu.setPreferredSize(new java.awt.Dimension(300, 30));
        btb_esqueceu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btb_esqueceuActionPerformed(evt);
            }
        });
        jPanel2.add(btb_esqueceu);

        jPanel1.add(jPanel2, new java.awt.GridBagConstraints());

        add(jPanel1, java.awt.BorderLayout.CENTER);
        add(mensagemSistema1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logarActionPerformed
        if(txt_login.getText().isEmpty()){
            txt_login.setBackground(new Color(255, 200, 180));
            mensagemSistema1.setMessageSistema("O campo login é obrigatório", "error");
        }
        
        if(ptxt_senha.getText().isEmpty()){
           ptxt_senha.setBackground(new Color(255, 200, 180));
            mensagemSistema1.setMessageSistema("O campo senha é obrigatório", "error"); 
        }
        
        mensagemSistema1.setMessageSistema("Aguarde...", "loading");
        
        Cliente userLogin = new Cliente();
        userLogin.setEmail(txt_login.getText());
        userLogin.setSenha(ptxt_senha.getText());
        
        LoginDAO login = new LoginDAO();
        
        new Thread(){
            @Override
            public void run(){
                clienteLogado = login.login(userLogin);
                
                if(clienteLogado.getId_Cliente() != null){
                    mensagemSistema1.setMessageSistema("Login efetuado com sucesso", "success");
                    newTela.isLogged(clienteLogado, true);
                }
                else{
                    mensagemSistema1.setMessageSistema("Login ou Senha incorretos!", "error");
                }
            }
         }.start();
        
    }//GEN-LAST:event_btn_logarActionPerformed

    private void btb_esqueceuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btb_esqueceuActionPerformed
        
        TelaEsqueceuSenha esqueceuSenha = new TelaEsqueceuSenha();
        newTela.addPanelContainer(esqueceuSenha);       
    }//GEN-LAST:event_btb_esqueceuActionPerformed
    
    public String NewPassword (){
        String letras = "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvYyWwXxZz1234567890!@#$%";
        Random random = new Random();
        String armazenaChaves = "";
        int index = -1;
        for( int i = 0; i < 9; i++ ) {
           index = random.nextInt( letras.length() );
           armazenaChaves += letras.substring( index, index + 1 );
        }
        return armazenaChaves;
    }
    
    public static void main(String args[]){
        JFrame janela = new JFrame();
        janela.setSize(550, 400);
        
        TelaLogin tela = new TelaLogin();
        janela.add(tela);
        janela.setVisible(true);
    }



    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btb_esqueceu;
    private javax.swing.JButton btn_logar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private projetointegrador1.MensagemSistema mensagemSistema1;
    private javax.swing.JTextField ptxt_senha;
    private javax.swing.JTextField txt_login;
    // End of variables declaration//GEN-END:variables
}
