/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import Cadastro_Cliente.Cliente;
import Cadastro_Cliente.ClienteDAO;
import java.util.Properties;
import java.util.Random;
import javax.mail.Address;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author natalia
 */
public class TelaEsqueceuSenha extends javax.swing.JPanel {

    /**
     * Creates new form TelaEsqueceuSenha
     */
    public TelaEsqueceuSenha() {
        initComponents();
        lblInstrucao.setText("<html>Digite o seu e-mail no campo abaixo e enviaremos uma<br> nova senha para você!</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblInstrucao = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        mensagemSistema1 = new projetointegrador1.MensagemSistema();

        setBackground(new java.awt.Color(102, 102, 0));
        setPreferredSize(new java.awt.Dimension(500, 300));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 276));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 228));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("   Esqueceu a Senha?");
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 29));
        jPanel2.add(jLabel1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));
        jPanel3.setPreferredSize(new java.awt.Dimension(380, 62));

        lblInstrucao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(lblInstrucao);

        jPanel2.add(jPanel3);

        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.setPreferredSize(new java.awt.Dimension(350, 30));
        jPanel2.add(txtEmail);

        jButton1.setBackground(new java.awt.Color(0, 204, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Enviar E-mail");
        jButton1.setPreferredSize(new java.awt.Dimension(250, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jPanel1.add(jPanel2, new java.awt.GridBagConstraints());

        add(jPanel1, java.awt.BorderLayout.CENTER);
        add(mensagemSistema1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Properties props = new Properties();
    /** Parâmetros de conexão com servidor Gmail */
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.socketFactory.port", "465");
        props.put("mail.smtp.socketFactory.class", 
        "javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.port", "465");

        Session session = Session.getDefaultInstance(props,
        
        new javax.mail.Authenticator() {
             protected PasswordAuthentication getPasswordAuthentication() 
             {
                   return new PasswordAuthentication("Smartmarketunivem@gmail.com", 
                   "S@martM@rket2019");
             }
        });
 
    /** Ativa Debug para sessão */
    session.setDebug(true);
 
    try {
            ClienteDAO cliente = new ClienteDAO();
            LoginDAO log = new LoginDAO();
            ClienteDAO cd = new ClienteDAO();
            String novaSenha = NewPassword();
            Cliente cl = cd.getByEmail(txtEmail.getText());
            if(cliente.CheckEmail(txtEmail.getText())){                            
                cl.setSenha(novaSenha);
                log.AlterarSenha(cl);
                Message message = new MimeMessage(session);
                message.setFrom(new InternetAddress("Smartmarketunivem@gmail.com")); 
                //Remetente      
                Address[] toUser = InternetAddress //Destinatário(s)
                           .parse(txtEmail.getText());//,nataliasilva@univem.edu.br  
                message.setRecipients(Message.RecipientType.TO, toUser);
                message.setSubject("Recuperação de senha");//Assunto
                message.setText("Você solicitou a recuperação de senha para sua conta\n"
                + "Aqui está sua nova senha:"  + novaSenha);
                /**Método para enviar a mensagem criada*/
                Transport.send(message);
                JOptionPane.showMessageDialog(null,"Senha do e-mail " + txtEmail.getText() + " foi alterada com sucesso");
            }else
            {
                JOptionPane.showMessageDialog(null,txtEmail.getText() + " não foi encontrado !\nAproveite e crie uma conta conosco"
                        + " é rápido e fácil");
            }
        }catch (MessagingException e) {
            System.out.println("ERROR: " + e);
            //throw new RuntimeException(e);                
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public String NewPassword (){
        String letras = "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvYyWwXxZz1234567890!@#$%";
        Random random = new Random();
        String armazenaChaves = "";
        int index = -1;
        for( int i = 0; i < 9; i++ ) {
           index = random.nextInt( letras.length() );
           armazenaChaves += letras.substring( index, index + 1 );
        }
        return armazenaChaves;
    }
    public static void main(String args[]){
        JFrame janela = new JFrame();
        janela.setSize(550, 400);
        
        TelaEsqueceuSenha tela = new TelaEsqueceuSenha();
        janela.add(tela);
        janela.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblInstrucao;
    private projetointegrador1.MensagemSistema mensagemSistema1;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
