/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lista;

import java.util.List;
import javax.swing.JFrame;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.swingbinding.JTableBinding;
import org.jdesktop.swingbinding.SwingBindings;
import projetointegrador1.NewTelaHome;

/**
 *
 * @author natalia
 */
public class TelaListas extends javax.swing.JPanel {

    private List<Lista> lstLista;
    private Lista selectedLista;
    private NewTelaHome newTela;
    
    /**
     * Creates new form TelaListas
     */
    
    public TelaListas(){
        ListaDAO ld = new ListaDAO();
                
        initComponents();
        
        lstLista = ld.listar();
        
        BindingGroup bg = new BindingGroup();
        JTableBinding tb = SwingBindings.createJTableBinding(
                    AutoBinding.UpdateStrategy.READ_WRITE,
                    lstLista, tabelaLista);
        
        JTableBinding.ColumnBinding cb = tb.addColumnBinding(BeanProperty.create("nome"));
        cb.setColumnName("Nome da Lista");
        cb.setColumnClass(String.class);
        
        bg.addBinding(tb);
        
        Binding b;
        b = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE,
                txtname, BeanProperty.create("text"),
                tabelaLista, BeanProperty.create("selectedElement.nome"));
        bg.addBinding(b);
        
        bg.bind();
        
        //Evento  chamado quando clica na linha da tabela
        tabelaLista.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(tabelaLista.getSelectedRow() > -1){
                    selectedLista = lstLista.get(tabelaLista.getSelectedRow());
                }
            }
        });
    }
    
    public TelaListas(NewTelaHome nth) {
        ListaDAO ld = new ListaDAO();
        
        this.newTela = nth;
        
        initComponents();
        
        txtname.setVisible(false);
        lblname.setVisible(false);
        btnSalvar.setVisible(false);
        
        lstLista = ld.listar();
        
        BindingGroup bg = new BindingGroup();
        JTableBinding tb = SwingBindings.createJTableBinding(
                    AutoBinding.UpdateStrategy.READ_WRITE,
                    lstLista, tabelaLista);
        
        JTableBinding.ColumnBinding cb = tb.addColumnBinding(BeanProperty.create("nome"));
        cb.setColumnName("Nome da Lista");
        cb.setColumnClass(String.class);
        
        bg.addBinding(tb);
        
        Binding b;
        b = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE,
                txtname, BeanProperty.create("text"),
                tabelaLista, BeanProperty.create("selectedElement.nome"));
        bg.addBinding(b);
        
        bg.bind();
        
        //Evento  chamado quando clica na linha da tabela
        tabelaLista.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(tabelaLista.getSelectedRow() > -1){
                    selectedLista = lstLista.get(tabelaLista.getSelectedRow());
                    
                    TelaListaProduto tlp = new TelaListaProduto(selectedLista);
                    newTela.addPanelContainer(tlp);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centralizador = new javax.swing.JPanel();
        principal = new javax.swing.JPanel();
        container_botoes = new javax.swing.JPanel();
        btnMostrarCadastro = new javax.swing.JButton();
        btnMostrarPesquisa = new javax.swing.JButton();
        container_acao = new javax.swing.JPanel();
        lblname = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        lblpesquisa = new javax.swing.JLabel();
        txtpesquisa = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaLista = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        centralizador.setPreferredSize(new java.awt.Dimension(400, 500));
        centralizador.setLayout(new java.awt.GridBagLayout());

        principal.setPreferredSize(new java.awt.Dimension(400, 500));

        container_botoes.setPreferredSize(new java.awt.Dimension(400, 50));

        btnMostrarCadastro.setBackground(new java.awt.Color(102, 102, 255));
        btnMostrarCadastro.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarCadastro.setText("Cadastrar Lista");
        btnMostrarCadastro.setPreferredSize(new java.awt.Dimension(190, 25));
        btnMostrarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarCadastroActionPerformed(evt);
            }
        });
        container_botoes.add(btnMostrarCadastro);

        btnMostrarPesquisa.setBackground(new java.awt.Color(102, 102, 255));
        btnMostrarPesquisa.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarPesquisa.setText("Pesquisar Lista");
        btnMostrarPesquisa.setPreferredSize(new java.awt.Dimension(190, 25));
        btnMostrarPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarPesquisaActionPerformed(evt);
            }
        });
        container_botoes.add(btnMostrarPesquisa);

        principal.add(container_botoes);

        container_acao.setBackground(new java.awt.Color(255, 255, 255));
        container_acao.setPreferredSize(new java.awt.Dimension(400, 50));

        lblname.setText("Nome da Lista: ");
        lblname.setPreferredSize(new java.awt.Dimension(80, 30));
        container_acao.add(lblname);

        txtname.setPreferredSize(new java.awt.Dimension(200, 30));
        container_acao.add(txtname);

        lblpesquisa.setText("Pesquisar Lista: ");
        lblpesquisa.setPreferredSize(new java.awt.Dimension(120, 30));
        container_acao.add(lblpesquisa);

        txtpesquisa.setPreferredSize(new java.awt.Dimension(220, 30));
        txtpesquisa.setRequestFocusEnabled(false);
        container_acao.add(txtpesquisa);

        btnPesquisar.setBackground(new java.awt.Color(255, 51, 51));
        btnPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/magnifying-glass.png"))); // NOI18N
        btnPesquisar.setLabel("");
        btnPesquisar.setPreferredSize(new java.awt.Dimension(40, 40));
        btnPesquisar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/magnifying-glass.png"))); // NOI18N
        container_acao.add(btnPesquisar);

        btnSalvar.setBackground(new java.awt.Color(0, 204, 0));
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.setPreferredSize(new java.awt.Dimension(80, 25));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        container_acao.add(btnSalvar);

        principal.add(container_acao);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 300));

        tabelaLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaLista.setFocusable(false);
        tabelaLista.setGridColor(new java.awt.Color(255, 255, 255));
        tabelaLista.setPreferredSize(new java.awt.Dimension(550, 280));
        tabelaLista.setRowHeight(22);
        tabelaLista.setSelectionBackground(new java.awt.Color(255, 204, 204));
        jScrollPane1.setViewportView(tabelaLista);

        principal.add(jScrollPane1);

        centralizador.add(principal, new java.awt.GridBagConstraints());

        add(centralizador, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Lista li = new Lista();
        li.setNome(txtname.getText());

        lstLista.add(li);

        ListaDAO lid = new ListaDAO();

        for(Lista ls:lstLista){
            if(ls.getId() == null){
                lid.inserir(ls);
            }
        }

        System.out.printf("Adicionado na lista: %s", li.getNome());
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnMostrarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarCadastroActionPerformed
        txtpesquisa.setVisible(false);
        lblpesquisa.setVisible(false);
        btnPesquisar.setVisible(false);
        
        txtname.setVisible(true);
        lblname.setVisible(true);
        btnSalvar.setVisible(true);
    }//GEN-LAST:event_btnMostrarCadastroActionPerformed

    private void btnMostrarPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarPesquisaActionPerformed
        txtname.setVisible(false);
        lblname.setVisible(false);
        btnSalvar.setVisible(false);
        
        txtpesquisa.setVisible(true);
        lblpesquisa.setVisible(true);
        btnPesquisar.setVisible(true);
    }//GEN-LAST:event_btnMostrarPesquisaActionPerformed
    
    public static void main(String args[]){
        JFrame janela = new JFrame();
        janela.setSize(550, 400);
        
        TelaListas tela = new TelaListas();
        janela.add(tela);
        janela.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrarCadastro;
    private javax.swing.JButton btnMostrarPesquisa;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JPanel centralizador;
    private javax.swing.JPanel container_acao;
    private javax.swing.JPanel container_botoes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblpesquisa;
    private javax.swing.JPanel principal;
    private javax.swing.JTable tabelaLista;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpesquisa;
    // End of variables declaration//GEN-END:variables
}
