/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lista;

import PesquisarProduto.Busca;
import PesquisarProduto.Produto;
import PesquisarProduto.ProdutoDAO;
import PesquisarProduto.RenderImage;
import Produto.TipoProduto;
import Produto.TipoProdutoDAO;
import java.util.LinkedList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.swingbinding.JTableBinding;
import org.jdesktop.swingbinding.SwingBindings;

/**
 *
 * @author natalia
 */
public class TelaListaProduto extends javax.swing.JPanel {
    
    List<ListaProduto> lstListaProdutos;
    List<TipoProduto> lstTipoProduto;
    Lista selectedLista;
    
    /**
     * Creates new form TelaListaProduto
     */
    public TelaListaProduto(Lista lista) {
        
        this.selectedLista = lista;
        
        lstListaProdutos = new LinkedList<>();
        lstListaProdutos = ObservableCollections.observableList(lstListaProdutos);
        
        initComponents();
        
        //Passando o nome da lista selecionada para o campo
        txtNameLista.setText(this.selectedLista.getNome());
        
        //Pegando os tipos de produtos cadastrado e listando no combobox
        TipoProdutoDAO tpd = new TipoProdutoDAO();
        
        lstTipoProduto = tpd.listar();
        
        for(TipoProduto tp:lstTipoProduto){
            cbTipoProduto.addItem(tp.getDescricao());
        }
        
        BindingGroup bg = new BindingGroup();
        JTableBinding tb = SwingBindings.createJTableBinding(AutoBinding.UpdateStrategy.READ_WRITE,
            lstListaProdutos, tabelaListaProdutos);
        
        tabelaListaProdutos.setRowHeight(50);
       
        JTableBinding.ColumnBinding cbImg = tb.addColumnBinding(BeanProperty.create("produto.imagem"));
        cbImg.setColumnName("Imagem");
        cbImg.setColumnClass(ImageIcon.class);
        
        JTableBinding.ColumnBinding cbDesc = tb.addColumnBinding(BeanProperty.create("tipoProduto.descricao"));
        cbDesc.setColumnName("Descrição");
        cbDesc.setColumnClass(String.class);
        
        JTableBinding.ColumnBinding cbProd = tb.addColumnBinding(BeanProperty.create("produto.nome"));
        cbProd.setColumnName("Produto");
        cbProd.setColumnClass(String.class);
        
        JTableBinding.ColumnBinding cbPrice = tb.addColumnBinding(BeanProperty.create("produto.preco"));
        cbPrice.setColumnName("Preço");
        cbPrice.setColumnClass(String.class);
        
        
        bg.addBinding(tb);
        
        bg.bind();
        
        tabelaListaProdutos.getColumnModel().getColumn(0).setCellRenderer(new RenderImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblNameLista = new javax.swing.JLabel();
        txtNameLista = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbTipoProduto = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaListaProdutos = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        mensagemSistema1 = new projetointegrador1.MensagemSistema();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setMinimumSize(new java.awt.Dimension(400, 40));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 500));
        jPanel2.setRequestFocusEnabled(false);

        lblNameLista.setText("Nome:");
        lblNameLista.setPreferredSize(new java.awt.Dimension(80, 30));
        jPanel2.add(lblNameLista);

        txtNameLista.setEditable(false);
        txtNameLista.setPreferredSize(new java.awt.Dimension(500, 30));
        txtNameLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameListaActionPerformed(evt);
            }
        });
        jPanel2.add(txtNameLista);

        jLabel3.setText("Produto: ");
        jLabel3.setPreferredSize(new java.awt.Dimension(80, 30));
        jPanel2.add(jLabel3);

        cbTipoProduto.setPreferredSize(new java.awt.Dimension(500, 30));
        jPanel2.add(cbTipoProduto);

        jPanel3.setPreferredSize(new java.awt.Dimension(500, 15));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3);

        jButton2.setText("Remover");
        jButton2.setPreferredSize(new java.awt.Dimension(160, 25));
        jPanel2.add(jButton2);

        jButton1.setText("Adicionar");
        jButton1.setPreferredSize(new java.awt.Dimension(160, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jPanel4.setPreferredSize(new java.awt.Dimension(500, 15));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(600, 250));

        tabelaListaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaListaProdutos.setPreferredSize(new java.awt.Dimension(600, 300));
        jScrollPane1.setViewportView(tabelaListaProdutos);

        jPanel2.add(jScrollPane1);

        jButton4.setBackground(new java.awt.Color(51, 51, 255));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/magnifying-glass.png"))); // NOI18N
        jButton4.setText("Buscar Preços");
        jButton4.setMinimumSize(new java.awt.Dimension(134, 30));
        jButton4.setPreferredSize(new java.awt.Dimension(190, 40));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        jButton5.setBackground(new java.awt.Color(0, 153, 102));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Salvar Lista");
        jButton5.setPreferredSize(new java.awt.Dimension(190, 40));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Apagar Lista");
        jButton3.setPreferredSize(new java.awt.Dimension(190, 40));
        jPanel2.add(jButton3);

        jPanel1.add(jPanel2, new java.awt.GridBagConstraints());

        add(jPanel1, java.awt.BorderLayout.CENTER);
        add(mensagemSistema1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameListaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TipoProduto tipoProduto = new TipoProduto();

        for(TipoProduto tp:lstTipoProduto){
            cbTipoProduto.addItem(tp.getDescricao());

            if(cbTipoProduto.getSelectedItem() == tp.getDescricao()){
                tipoProduto = tp;
            }
        }

        Produto produto = new Produto();

        ListaProduto listaProduto = new ListaProduto();
        listaProduto.setLista(this.selectedLista);
        listaProduto.setTipoProduto(tipoProduto);
        listaProduto.setProduto(produto);

        lstListaProdutos.add(listaProduto);

        ListaProdutoDAO lpDAO = new ListaProdutoDAO();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        Busca busca = new Busca();

        busca.getProduct(lstListaProdutos, mensagemSistema1);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        for(ListaProduto lp:lstListaProdutos){
            
            ProdutoDAO pDAO = new ProdutoDAO();
            pDAO.inserir(lp.getProduto());
            
            ListaProdutoDAO lpDAO = new ListaProdutoDAO();
            lpDAO.inserir(lp);
        
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed
    
    public static void main(String args[]){
        JFrame janela = new JFrame();
        janela.setSize(550, 400);
        
        //TelaListaProduto tela = new TelaListaProduto();
        //janela.add(tela);
        //janela.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbTipoProduto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNameLista;
    private projetointegrador1.MensagemSistema mensagemSistema1;
    private javax.swing.JTable tabelaListaProdutos;
    private javax.swing.JTextField txtNameLista;
    // End of variables declaration//GEN-END:variables
}
